version: '3.7'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: .
    command: sh -c "python3 /usr/src/proj/manage.py makemigrations && 
                    python3 /usr/src/proj/manage.py migrate && 
                    python3 /usr/src/proj/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: